services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - "27017:27017" 
    networks:
      - my_network
    env_file:
      - ./Env/Mongo/.env
    volumes:
      - mongo_data:/data/db
  node:
    container_name: node-app
    restart: always
    build:
      context: ./
      target: ${ENVIRONMENT}
    networks:
      - my_network
    ports:
      - "3000:3000" 
    working_dir: /usr/src/app
    volumes:
      - ./app:/usr/src/app 
    depends_on:
      - mongo
    env_file:
      - ./Env/Node/.env
    # acessar container node
    # docker exec -it node-app sh

networks:
  my_network:
    driver: bridge
volumes:
  mongo_data:
    driver: local
